from django.urls import path
from . import default_views

app_name = 'school_app'

urlpatterns = [
    path('', default_views.home, name='home'),
    path('register-student/', default_views.register_student, name='register_student'),
    path('complete-student-registration/', default_views.complete_student_registration, name='complete_student_registration'),
    path('register-teacher/', default_views.register_teacher, name='register_teacher'),
    path('complete-teacher-registration/', default_views.complete_teacher_registration, name='complete_teacher_registration'),
    path('assign_registration_number/<int:student_id>/', default_views.assign_registration_number, name='assign_registration_number'),
    path('login/', default_views.login_view, name='login'),
    path('logout/', default_views.logout_view, name='logout'),
    path('admin-dashboard/', default_views.admin_dashboard, name='admin-dashboard'),
    path('teacher-dashboard/', default_views.teacher_dashboard, name='teacher-dashboard'),
    path('student-dashboard/', default_views.student_dashboard, name='student-dashboard'),
    path('classarm/create/', default_views.create_class_arm, name='create_class_arm'),
    path('classarm/assign-teacher/', default_views.assign_teacher_class_arm, name='assign_teacher_class'),
    path('classarm/assign-student/', default_views.assign_student_class_arm, name = 'assign_student_class'),
    path('subjects/register/', default_views.register_subjects, name = 'register_subjects'),
    path('subjects/assign-class-subject/', default_views.assign_class_subject, name='assign_class_subject'),
    path('subjects/view/<int:class_arm_id>/', default_views.view_class_subjects, name = 'view-subjects'),
    path('create-assignment/', default_views.create_midterm_assignment, name = 'create_midterm_assignment'),
    path('view-assignments/<int:class_arm_id>/', default_views.view_midterm_assignments, name = 'view_midterm_assignment'),
    path('view-assignment/<int:assignment_id>/', default_views.view_each_midterm_assignment, name='view_each_midterm_assignment'),
    path('delete-assignment/<int:assignment_id>/', default_views.delete_midterm_assignment, name='delete_midterm_assignment'),
    path('enter-scores/<int:class_arm_id>/', default_views.enter_scores, name = 'enter-scores'),
    path('results/', default_views.student_results, name='student-results'),
    path('student/profile/', default_views.student_profile, name='student_profile'),
    path('student/profile/edit/', default_views.edit_student_profile, name='edit_student_profile'),
    path('teacher/profile/', default_views.teacher_profile, name='teacher_profile'),
    path('teacher/profile/edit/', default_views.edit_teacher_profile, name='edit_teacher_profile'),
    path('admin-profile/', default_views.admin_profile, name='admin_profile'),
    path('admin-profile/edit/', default_views.edit_admin_profile, name='edit_admin_profile'),
    path('students/', default_views.view_students, name='view_students'),
    path('teachers/', default_views.view_teachers, name='view_teachers'),
    path('classarms/', default_views.view_all_class_arms, name='view_all_class_arms'),
    path('classarm/<int:class_arm_id>/', default_views.view_classarm, name='view_classarm'),
    path('classarm/<int:class_arm_id>/delete/', default_views.delete_class_arm, name='delete_class_arm'),
    path('classarm/<int:class_arm_id>/students/', default_views.view_students_in_class_arm, name='view_students_in_class_arm'),
    path('subjects/', default_views.view_all_subjects, name='view_all_subjects'),
    path('subject/<int:subject_id>/delete/', default_views.delete_subject, name='delete_subject'),
    path('teacher/<int:teacher_id>/delete/', default_views.delete_teacher, name='delete_teacher'),
    path('teacher/<int:teacher_id>/update-class-arm/', default_views.update_teacher_class_arm, name='update_teacher_class_arm'),
    path('student/<int:student_id>/delete/', default_views.delete_student, name='delete_student'),
    path('student/<int:student_id>/promote/', default_views.promote_students, name='promote_student'),
    path('teacher/<int:teacher_id>/remove-class-arm/', default_views.remove_teacher_class_arm, name='remove_teacher_class_arm'),
    path('student/<int:student_id>/remove-class-arm/', default_views.remove_student_class_arm, name='remove_student_class_arm'),
    path('results/<int:student_id>/', default_views.view_student_results_as_teacher, name='view_student_results_as_teacher'),
    path('enter-scores/<int:class_arm_id>/',   default_views.enter_scores, name='enter_scores'),
    path('enter-scores/student/<int:student_id>/', default_views.enter_student_scores, name='enter_student_scores'),
    path('admin-view-results/', default_views.admin_view_results, name='admin_view_results'),
    path('admin-view-results/results/<int:student_id>/', default_views.view_student_results_as_admin, name='admin_view_student_results'),
    path('results/download/', default_views.download_student_results_pdf, name='download-student-results-pdf'),
    path('term/start/', default_views.start_new_term, name='start_new_term'),
]