# Generated by Django 6.0.1 on 2026-02-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classarm',
            name='teacher',
        ),
    ]
