# Generated by Django 6.0.1 on 2026-02-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_remove_classarm_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='Teacher_id_number',
        ),
    ]
