# Generated by Django 6.0.1 on 2026-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_remove_teacherprofile_teacher_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_arms',
            field=models.ManyToManyField(blank=True, to='school_app.classarm'),
        ),
    ]
