# Generated by Django 6.0.1 on 2026-09-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_academicsession_result_session_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_app.classarm'),
        ),
    ]
