# Generated by Django 6.0.1 on 2026-09-16 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_alter_studentprofile_class_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermassignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional. PDF or Word document, up to 10MB.', null=True, upload_to='assignments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
